"""initial schema

Revision ID: 0001
Revises: 
Create Date: 2026-09-15 20:37:11.105127
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = '0001'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('companies',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('company_name', sa.String(length=500), nullable=False),
    sa.Column('normalized_name', sa.String(length=500), nullable=False),
    sa.Column('country', sa.String(length=150), nullable=True),
    sa.Column('city', sa.String(length=150), nullable=True),
    sa.Column('region', sa.String(length=100), nullable=True),
    sa.Column('website', sa.String(length=500), nullable=True),
    sa.Column('domain', sa.String(length=300), nullable=True),
    sa.Column('industry', sa.String(length=150), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('activities', sa.JSON(), nullable=False),
    sa.Column('products', sa.JSON(), nullable=False),
    sa.Column('keywords', sa.JSON(), nullable=False),
    sa.Column('source', sa.String(length=100), nullable=True),
    sa.Column('source_url', sa.String(length=1000), nullable=True),
    sa.Column('relevance_score', sa.Integer(), nullable=False),
    sa.Column('discovered_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('exported_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('companies', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_companies_city'), ['city'], unique=False)
        batch_op.create_index(batch_op.f('ix_companies_country'), ['country'], unique=False)
        batch_op.create_index(batch_op.f('ix_companies_domain'), ['domain'], unique=False)
        batch_op.create_index(batch_op.f('ix_companies_exported_at'), ['exported_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_companies_industry'), ['industry'], unique=False)
        batch_op.create_index(batch_op.f('ix_companies_normalized_name'), ['normalized_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_companies_region'), ['region'], unique=False)
        batch_op.create_index(batch_op.f('ix_companies_relevance_score'), ['relevance_score'], unique=False)

    op.create_table('saved_searches',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('region', sa.String(length=100), nullable=True),
    sa.Column('country', sa.String(length=150), nullable=True),
    sa.Column('city', sa.String(length=150), nullable=True),
    sa.Column('industry', sa.String(length=150), nullable=True),
    sa.Column('activity', sa.String(length=150), nullable=True),
    sa.Column('products', sa.JSON(), nullable=False),
    sa.Column('keywords', sa.JSON(), nullable=False),
    sa.Column('result_limit', sa.Integer(), nullable=False),
    sa.Column('frequency', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_run_at', sa.DateTime(), nullable=True),
    sa.Column('next_run_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('saved_searches', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_saved_searches_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_saved_searches_next_run_at'), ['next_run_at'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=200), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    op.create_table('company_contacts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('company_id', sa.String(length=36), nullable=False),
    sa.Column('contact_page_url', sa.String(length=1000), nullable=True),
    sa.Column('contact_person_name', sa.String(length=200), nullable=True),
    sa.Column('contact_person_title', sa.String(length=200), nullable=True),
    sa.Column('discovered_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('company_contacts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_company_contacts_company_id'), ['company_id'], unique=True)

    op.create_table('company_emails',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('company_id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('is_valid', sa.Boolean(), nullable=True),
    sa.Column('discovered_at', sa.DateTime(), nullable=False),
    sa.Column('exported_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('company_emails', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_company_emails_company_id'), ['company_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_company_emails_exported_at'), ['exported_at'], unique=False)

    op.create_table('company_phones',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('company_id', sa.String(length=36), nullable=False),
    sa.Column('phone', sa.String(length=50), nullable=False),
    sa.Column('is_valid', sa.Boolean(), nullable=False),
    sa.Column('discovered_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('company_phones', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_company_phones_company_id'), ['company_id'], unique=False)

    op.create_table('company_sources',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('company_id', sa.String(length=36), nullable=False),
    sa.Column('source', sa.String(length=100), nullable=False),
    sa.Column('source_url', sa.String(length=1000), nullable=True),
    sa.Column('raw_company_name', sa.String(length=500), nullable=True),
    sa.Column('match_confidence', sa.Float(), nullable=True),
    sa.Column('discovered_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('company_sources', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_company_sources_company_id'), ['company_id'], unique=False)

    op.create_table('credit_transactions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('delta', sa.Integer(), nullable=False),
    sa.Column('reason', sa.String(length=50), nullable=False),
    sa.Column('detail', sa.String(length=500), nullable=True),
    sa.Column('balance_after', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('credit_transactions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_credit_transactions_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_credit_transactions_user_id'), ['user_id'], unique=False)

    op.create_table('lead_scores',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('company_id', sa.String(length=36), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('relevance_component', sa.Integer(), nullable=False),
    sa.Column('contact_completeness_component', sa.Integer(), nullable=False),
    sa.Column('verified_email_component', sa.Integer(), nullable=False),
    sa.Column('verified_phone_component', sa.Integer(), nullable=False),
    sa.Column('computed_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('lead_scores', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_lead_scores_company_id'), ['company_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_lead_scores_score'), ['score'], unique=False)

    op.create_table('search_queries',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('region', sa.String(length=100), nullable=True),
    sa.Column('country', sa.String(length=150), nullable=True),
    sa.Column('city', sa.String(length=150), nullable=True),
    sa.Column('industry', sa.String(length=150), nullable=True),
    sa.Column('activity', sa.String(length=150), nullable=True),
    sa.Column('products', sa.JSON(), nullable=False),
    sa.Column('keywords', sa.JSON(), nullable=False),
    sa.Column('result_limit', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'RUNNING', 'COMPLETED', 'FAILED', name='searchstatus', native_enum=False), nullable=False),
    sa.Column('status_message', sa.String(length=500), nullable=True),
    sa.Column('result_count', sa.Integer(), nullable=False),
    sa.Column('new_company_count', sa.Integer(), nullable=False),
    sa.Column('duplicate_count', sa.Integer(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('saved_search_id', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['saved_search_id'], ['saved_searches.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('search_queries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_search_queries_saved_search_id'), ['saved_search_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_search_queries_status'), ['status'], unique=False)

    op.create_table('social_profiles',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('company_id', sa.String(length=36), nullable=False),
    sa.Column('platform', sa.String(length=50), nullable=False),
    sa.Column('url', sa.String(length=1000), nullable=False),
    sa.Column('discovered_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('social_profiles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_social_profiles_company_id'), ['company_id'], unique=False)

    op.create_table('subscriptions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('plan', sa.String(length=50), nullable=False),
    sa.Column('credits_per_month', sa.Integer(), nullable=False),
    sa.Column('credits_balance', sa.Integer(), nullable=False),
    sa.Column('period_started_at', sa.DateTime(), nullable=False),
    sa.Column('renews_at', sa.DateTime(), nullable=False),
    sa.Column('discovery_day', sa.String(length=10), nullable=True),
    sa.Column('discovery_searches_today', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('subscriptions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_subscriptions_user_id'), ['user_id'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subscriptions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_subscriptions_user_id'))

    op.drop_table('subscriptions')
    with op.batch_alter_table('social_profiles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_social_profiles_company_id'))

    op.drop_table('social_profiles')
    with op.batch_alter_table('search_queries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_search_queries_status'))
        batch_op.drop_index(batch_op.f('ix_search_queries_saved_search_id'))

    op.drop_table('search_queries')
    with op.batch_alter_table('lead_scores', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_lead_scores_score'))
        batch_op.drop_index(batch_op.f('ix_lead_scores_company_id'))

    op.drop_table('lead_scores')
    with op.batch_alter_table('credit_transactions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_credit_transactions_user_id'))
        batch_op.drop_index(batch_op.f('ix_credit_transactions_created_at'))

    op.drop_table('credit_transactions')
    with op.batch_alter_table('company_sources', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_company_sources_company_id'))

    op.drop_table('company_sources')
    with op.batch_alter_table('company_phones', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_company_phones_company_id'))

    op.drop_table('company_phones')
    with op.batch_alter_table('company_emails', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_company_emails_exported_at'))
        batch_op.drop_index(batch_op.f('ix_company_emails_company_id'))

    op.drop_table('company_emails')
    with op.batch_alter_table('company_contacts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_company_contacts_company_id'))

    op.drop_table('company_contacts')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    with op.batch_alter_table('saved_searches', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_saved_searches_next_run_at'))
        batch_op.drop_index(batch_op.f('ix_saved_searches_is_active'))

    op.drop_table('saved_searches')
    with op.batch_alter_table('companies', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_companies_relevance_score'))
        batch_op.drop_index(batch_op.f('ix_companies_region'))
        batch_op.drop_index(batch_op.f('ix_companies_normalized_name'))
        batch_op.drop_index(batch_op.f('ix_companies_industry'))
        batch_op.drop_index(batch_op.f('ix_companies_exported_at'))
        batch_op.drop_index(batch_op.f('ix_companies_domain'))
        batch_op.drop_index(batch_op.f('ix_companies_country'))
        batch_op.drop_index(batch_op.f('ix_companies_city'))

    op.drop_table('companies')
    # ### end Alembic commands ###
