"""payment reference

Every payment order gets a short reference code generated by the app, so a
customer can mark an order paid without typing a blockchain transaction ID.
Existing orders are given a reference too.

Revision ID: 0004
Revises: 0003
Create Date: 2026-09-16
"""

from __future__ import annotations

import secrets
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "0004"
down_revision: str | None = "0003"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

# No look-alike characters (no O/0, I/1), so a reference is easy to read out.
ALPHABET = "ABCDEFGHJKLMNPQRSTUVWXYZ23456789"


def _reference(taken: set[str]) -> str:
    while True:
        candidate = "PL-" + "".join(secrets.choice(ALPHABET) for _ in range(8))
        if candidate not in taken:
            taken.add(candidate)
            return candidate


def upgrade() -> None:
    with op.batch_alter_table("payment_orders") as batch_op:
        batch_op.add_column(sa.Column("reference", sa.String(length=20), nullable=True))

    conn = op.get_bind()
    taken: set[str] = set()
    for (order_id,) in conn.execute(
        sa.text("SELECT id FROM payment_orders WHERE reference IS NULL")
    ).fetchall():
        conn.execute(
            sa.text("UPDATE payment_orders SET reference = :reference WHERE id = :id"),
            {"reference": _reference(taken), "id": order_id},
        )

    with op.batch_alter_table("payment_orders") as batch_op:
        batch_op.alter_column("reference", existing_type=sa.String(length=20), nullable=False)
        batch_op.create_index("ix_payment_orders_reference", ["reference"], unique=True)


def downgrade() -> None:
    with op.batch_alter_table("payment_orders") as batch_op:
        batch_op.drop_index("ix_payment_orders_reference")
        batch_op.drop_column("reference")
